services:
  - type: web
    name: plant-disease-server
    rootDir: server
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn backend:app --bind 0.0.0.0:$PORT
    envVars:
      - name: PYTHON_VERSION
        value: 3.10
    plan: standard
